# Dockerfile

# Stage 1: Development
FROM node:22-alpine AS dev

WORKDIR /app

COPY package*.json ./

# Install all dependencies, including devDependencies
RUN npm install --include=dev

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
